### ISSUE TITLE
data.table update to do "correct" column dispatch in all.equal() breaks dtts

### ISSUE THREAD

**Issue by MichaelChirico** [eddelbuettel/dtts#17]
https://github.com/Rdatatable/data.table/issues/6285

In https://github.com/Rdatatable/data.table/pull/4546, we changed `all.equal.data.table()` to run each column's `all.equal()` method, as appropriate. Our own suite was hiding some really glaring issues where previously integer64 columns were being compared on their double representation --> horribly wrong test.

At a glance, it looks like the new behavior will be welcome here as well.

This will be released to CRAN ~soon. Since I think the new behavior is strictly more correct, I would appreciate your help pushing a new version to avoid a clunky back-compatibility hack.

I am taking a look at reproducing & filing a PR now, but if the fix is immediately obvious to you, feel free to flag & take over.

Thanks!

**Comment by eddelbuettel** [comment]
I am a bit tied up (as I presume @lsilvest is) so help with a PR would be appreciated, as always.

Otherwise: Ack. We stand pat to jump in as needed.

**Comment by eddelbuettel** [comment]
This is now fixed in the new CRAN version -- thanks again for the PR.

![image](https://github.com/user-attachments/assets/79bd5ba2-c7bc-481c-b5ef-56c9741fad24)
